--- # The Header starts after this line
  version: 1        # All tasks, like plugins, have versioning
  schedule:         # How frequently should we run this task?
    type: "simple"  # Simple means run forever at the interval below
    interval: "1s"  # This accepts seconds ('s') and milliseconds  ('ms')
  workflow:           # For a small number of statistics, we have tests as small
    collect:          # as 10ms. For a large number, more than 1s may be needed.
      metrics:        # Collector caching defaults to 500ms.
        /intel/psutil/load/load1: {}   # Here are the specific metrics we collect
        /intel/psutil/load/load15: {}    # out of the set of all available from
        /intel/psutil/load/load5: {}     # our installed plugins. This list only
        /intel/psutil/vm/available: {}   # requires psutil but could be more.
        /intel/psutil/vm/free: {}
        /intel/psutil/vm/used: {}
      config:
      process:      # Process is an optional part of the workflow. After collection,
        -           # we have the option to have one or more processors followed by publishers
          plugin_name: "passthru"
          process: null
          publish:
            -
              plugin_name: "file"
              config:
                file: "/tmp/snap_published_demo_file.log"
