language: go
go:
- 1.3.1
- tip
before_install:
- cp .netrc ~
- chmod 600 .netrc
install:
- go get -v github.com/smartystreets/goconvey # Get goconvey
- go get code.google.com/p/go.tools/cmd/cover # get golang cover
- go get -d -v ./... && go build -v ./... # get and build source
- ls /home/travis/gopath/src/github.com/intelsdilabs/pulse # change dir into source
script: go test ./... -v -cover # run go test with cover
notifications:
  slack:
    secure: VkbZLIc2RH8yf3PtIAxUNPdAu3rQQ7yQx0GcK124JhbEnZGaHyK615V0rbG7HcVmYKGPdB0cXqZiLBDKGqGKb2zR1NepOe1nF03jxGSpPq8jIFeEXSJGEYGL34ScDzZZGuG6qwbjFcXiW5lqn6t8igzp7v2+URYBaZo5ktCS2xY=
